#
#
#	Container makefile (main)
#
#

CCC = g++
CCFLAGS = -ansi

LinkedList_Container:
	rm -f common.h common.cc entry.h
	rm -f container.h container.cc listnode.h listnode_inl.h
	rm -f container.h container.cc listnode.h listnode_inl.h
	rm -f container.h container.cc listnode.h listnode_inl.h
	rm -f container.h container.cc listnode.h listnode_inl.h
	ln -s Common/common.h
	ln -s Common/common.cc
	ln -s Common/entry.h
	ln -s LinkedList/container.h
	ln -s LinkedList/container.cc
	ln -s LinkedList/listnode.h
	ln -s LinkedList/listnode_inl.h
	

clean:
	rm -f *.o

real_clean: clean
	rm -f testcontainer
